[wip] Bitmask in rust
artichoke/artichoke pull request #1101
Opened 2021-02-21 05:23 UTC by sudopluto

work in progress for #1084

2021-02-23 15:27 UTC, lopopolo requested changes
This looks great! Let's remove the `Result` wrapper from these functions since they are infallible.

2021-02-23 15:27 UTC, lopopolo commented on artichoke-backend/src/extn/core/integer/mod.rs
> +        Ok(self.as_i64() & mask == mask)
This function doesn't need to be fallible:

```suggestion
    pub fn is_allbits(self, mask: Int) -> bool {
        self.as_i64() & mask == mask
```

2021-02-23 15:27 UTC, lopopolo commented on artichoke-backend/src/extn/core/integer/mod.rs
> +        Ok(self.as_i64() & mask != 0)
This function doesn't need to be fallible:

```suggestion
    pub fn is_anybits(self, mask: Int) -> bool {
        self.as_i64() & mask != 0
```

2021-02-23 15:27 UTC, lopopolo commented on artichoke-backend/src/extn/core/integer/mod.rs
> +        Ok(self.as_i64() & mask == 0)
This function doesn't need to be fallible:

```suggestion
    pub fn is_nobits(self, mask: Int) -> bool {
        self.as_i64() & mask == 0
```

2021-02-23 16:40 UTC, sudopluto commented
cool, will do. do I need unit tests? probably not right?

2021-02-23 16:46 UTC, lopopolo commented
> cool, will do. do I need unit tests? probably not right?

This is simple enough where I think we can land it without unit tests.

2021-02-28 02:14 UTC, lopopolo approved these changes
Looks good to me, but I think clippy is upset about something (I'm on mobile and can't see the build log)

2021-02-28 14:10 UTC, lopopolo approved these changes

2021-02-28 14:10 UTC, merged