Add global hasher
artichoke/artichoke pull request #1488
Opened 2021-11-06 17:15 UTC by masonforest

> 😄 you might want to take a look at:
>Add a 'perl hash' implementation to spinoso-string #1450
>https://twitter.com/artichokeruby/status/1444089207547330562

Awesome! It's like we're Indiana Jonesing hashing algorithms haha. Let me know if this needs anything else!

Closes #1404

2021-11-06 17:31 UTC, lopopolo requested changes
Thanks for the PR @masonforest.

It looks like I communicated poorly around the associated type parameter for the build hasher. A couple of tweaks and I think this will be good to go.

In case you're not familiar with associated types in traits, this is what they refer to:

https://doc.rust-lang.org/rust-by-example/generics/assoc_items/types.html

2021-11-06 17:31 UTC, lopopolo commented on artichoke-core/src/hash.rs
> +    type Error;
oh sorry I may have led you down a confusing path here.

Adding a generic parameter to the trait means that `BuildHasher` can be implemented multiple times for a given interpreter with multiple `BuildHasher` type params. This isn't quite the API I was hoping for.

Instead, like we have the associated `Error` type here, implementors of `BuildHasher` should declare exactly 1 `BuildHasher` type they use.

Something like this:

```suggestion
pub trait BuildHasher {
    /// Concrete error type for errors encountered when outputting hash errors.
    type Error;
    
    /// Concrete build hasher type.
    type BuildHasher: core::hash::BuildHasher;
```

This also uses the `BuildHasher` import via `core` so `artichoke-core` continues to be compilable with no-std.

This structure with associated types is used pretty heavily in `artichoke-core`, for example the PRNG in the `Prng` trait:

https://github.com/artichoke/artichoke/blob/1c1702894e6ef237b8d7644c16f6b1bc9ae5f5e7/artichoke-core/src/prng.rs#L10-L11

2021-11-06 17:31 UTC, lopopolo commented on artichoke-backend/src/hash.rs
> +    type Error = Error;
To match the change proposed below:

```suggestion
impl BuildHasher for Artichoke {
    type Error = Error;
    type BuildHasher = RandomState;
```

2021-11-06 17:31 UTC, lopopolo commented on artichoke-backend/src/hash.rs
> +    fn build_hasher(&mut self) -> Result<&RandomState, Self::Error> {
style nit, I prefer using the associated types here to mirror the trait definition:

```suggestion
    fn build_hasher(&mut self) -> Result<&Self::BuildHasher, Self::Error> {
```

2021-11-06 17:31 UTC, lopopolo commented on artichoke-backend/src/lib.rs
> +pub mod hash;
there's nothing here to export, there's only a trait implementation, so let's not make this `pub` like `globals` and `intern` below.

```suggestion
mod hash;
```

2021-11-06 17:35 UTC, lopopolo commented on artichoke-core/src/hash.rs
> +    type Error;
another reason to prefer an associated item here:

If I'm building part of the standard library that wants to generically constrain the Artichoke interpreter to include a hasher, most of the time I don't care what `BuildHasher` is used, just that the trait is implemented.

Having the generic parameter in the trait means it must be named, even if all we do is add `where B: core::hash::BuildHasher`. Using an associated type with that same bound improves the ergonomics a bit.

2021-11-06 19:40 UTC, masonforest commented
Ah, I should have read more carefully. You did say to use an associated type in your feedback.

I think this should be getting close now.

2021-11-06 23:09 UTC, lopopolo approved these changes
This looks great. Thanks!

I'll merge once CI passes.

2021-11-06 23:18 UTC, lopopolo commented
It looks like rustfmt failed. If you run this locally it should fix everything up:

```shell
bundle install
bundle exec rake
```

Or if you don't have Ruby, it looks like all it needs is a:

```shell
cargo fmt
```

2021-11-07 02:51 UTC, lopopolo commented
Sorry for the back and forth here. I hope you don't mind that I've tweaked your branch to add the docs and clean things up a bit. Once the tests pass, this is good to go.

2021-11-07 02:51 UTC, lopopolo commented
this PR bumps `artichoke-core` to version 0.10.0.

2021-11-07 03:19 UTC, merged